/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import javax.swing.JOptionPane;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 *
 * @author Administrator
 */
public class MyJPanel extends javax.swing.JPanel implements TreeSelectionListener {

    /**
     * Creates new form MyJPanel
     */
    public MyJPanel() {
        initComponents();
    }

    public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();
        if (node.isLeaf()) {
            String str = node.toString();
            if (str.equals("录入学生信息"))//增加监听
            {
                //System.out.println("ok");
                p1 = new LuruJPanel();
                jSplitPane1.setRightComponent(p1);
            } else if (str.equals("查询学生信息")) {
                //jSplitPane1.remove(p1);
                ChaxunJPanel lp = new ChaxunJPanel();
                jSplitPane1.setRightComponent(lp);
                jSplitPane1.validate();
            } else if (str.equals("修改学生信息")) {
                //jSplitPane1.remove(p1);
                XiugaiJPanel qp = new XiugaiJPanel();
                jSplitPane1.setRightComponent(qp);
                jSplitPane1.validate();
            } else if (str.equals("删除学生信息")) {
                ShanchuJPanel sp = new ShanchuJPanel();
                jSplitPane1.setRightComponent(sp);
                jSplitPane1.validate();
            } else if (str.equals("信息管理")) {
                FristJPanel xx = new FristJPanel();
                jSplitPane1.setRightComponent(xx);
                jSplitPane1.validate();
            } else if (str.equals("录入课程信息")) {
                Luru2JPanel lu = new Luru2JPanel();
                jSplitPane1.setRightComponent(lu);
                jSplitPane1.validate();
            } else if (str.equals("修改课程信息")) {
                Xiugai2JPanel xg = new Xiugai2JPanel();
                jSplitPane1.setRightComponent(xg);
                jSplitPane1.validate();
            } else if (str.equals("删除课程信息")) {
                Shanchu2JPanel ss = new Shanchu2JPanel();
                jSplitPane1.setRightComponent(ss);
                jSplitPane1.validate();
            } else if (str.equals("学生成绩登入")) {
                ChengjiJPanel cj = new ChengjiJPanel();
                jSplitPane1.setRightComponent(cj);
                jSplitPane1.validate();
            } else if (str.equals("学生成绩修改")) {
                Xiugai3JPanel xg3 = new Xiugai3JPanel();
                jSplitPane1.setRightComponent(xg3);
                jSplitPane1.validate();
            } 
            else if (str.equals("修改密码")) {
                MimaJPanel mm = new MimaJPanel();
                jSplitPane1.setRightComponent(mm);
                jSplitPane1.validate();
            } else if (str.equals("退出系统")) {
                int n = JOptionPane.showConfirmDialog(this, "是否退出系统？", "提示", JOptionPane.YES_NO_OPTION);
                    if (n == JOptionPane.YES_OPTION) {
                        FristJPanel z2 = new FristJPanel();
                        MyJFrame.jf.remove(MyJFrame.jf.getContentPane());
                        MyJFrame.jf.setContentPane(z2);
                        MyJFrame.jf.validate();
                    } else if (n == JOptionPane.NO_OPTION) {

                    }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(87, 164, 249));
        setPreferredSize(new java.awt.Dimension(700, 600));

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" 学生信息管理系统");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(160, 100));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jTree1.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("信息管理");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("学籍管理");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("录入学生信息");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("查询学生信息");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("修改学生信息");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("删除学生信息");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("课程管理");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("录入课程信息");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("修改课程信息");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("删除课程信息");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("成绩管理");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("学生成绩登入");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("学生成绩修改");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("账号管理");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("修改密码");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("退出系统");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.setAlignmentX(1.0F);
        jTree1.setAlignmentY(1.0F);
        jTree1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTree1.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jTree1.addTreeSelectionListener(this);
        jScrollPane1.setViewportView(jTree1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel3.setFont(new java.awt.Font("华文行楷", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("欢迎进入学生信息管理系统");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/20160929110748.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
    LuruJPanel p1;
}
