 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static test.FristJPanel.myid;

/**
 *
 * @author Administrator
 */
public class SchaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterJPanel
     */
    public SchaJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        jScrollPane1.setViewportView(jEditorPane1);

        setBackground(new java.awt.Color(229, 229, 234));

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("成绩信息查询");

        jLabel8.setFont(new java.awt.Font("黑体", 0, 16)); // NOI18N
        jLabel8.setText("请输入课程编号：");

        jTextField11.setFont(new java.awt.Font("黑体", 0, 16)); // NOI18N

        jButton3.setFont(new java.awt.Font("黑体", 0, 16)); // NOI18N
        jButton3.setText("查询");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextArea1.setBackground(new java.awt.Color(255, 255, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jTextArea1.setOpaque(false);
        jScrollPane2.setViewportView(jTextArea1);

        jButton1.setFont(new java.awt.Font("黑体", 0, 16)); // NOI18N
        jButton1.setText("全部查询");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String s = jTextField11.getText().trim();
        int id = myid;
        try {
            String sql2 = "select * from course where  courseid = '" + s + "'";
            Statement st = DBCon.DBconnec().createStatement();
            ResultSet rs1 = st.executeQuery(sql2);
            int count = 0;
            String sql3 = "select sc from sc where id = '"+id+"' and courseid = '"+s+"'";
            Statement st2 = DBCon.DBconnec().createStatement();
            ResultSet rs3 = st2.executeQuery(sql3);
            int count3 =0;
            while (rs1.next()) {
                count = rs1.getInt(1);
            }
            while (rs3.next()) {
                count3 = rs3.getInt(1);
            }
            if (count == 0) {
                JOptionPane.showMessageDialog(this, "该课程编号不存在", "Error", JOptionPane.ERROR_MESSAGE);
                jTextArea1.setText("");
            } else if (count3 == 0) {
                JOptionPane.showMessageDialog(this, "该门课程成绩不存在", "Error", JOptionPane.ERROR_MESSAGE);
                jTextArea1.setText("");
            }else {
                try {
                    jTextArea1.setText("");
                    Connection sta = DBCon.DBconnec();
                    PreparedStatement ps = sta.prepareStatement("select info.id,info.`name`,course.courseid,course.coursename,course.teacher,course.xz,sc.sc from info,sc,course,susers where info.id =sc.id and sc.courseid=course.courseid and info.id = susers.id and course.courseid=" + s + " and info.id=?");
                    ps.setInt(1, myid);
                    ResultSet rs = ps.executeQuery();
                    while (rs.next()) {
                        int s1 = rs.getInt(1);
                        String s2 = rs.getString(2);
                        String s3 = rs.getString(3);
                        String s4 = rs.getString(4);
                        String s5 = rs.getString(5);
                        String s6 = rs.getString(6);
                        int s7 = rs.getInt(7);
                        jTextArea1.append("学号：" + s1 + " 姓名：" + s2 + ";课程编号：" + s3 + ";课程名称：" + s4 + ";课程教师：" + s5 + ";课程性质：" + s6 + ";成绩：" + s7 + "\r\n");
                    }
                } catch (Exception e) {
                    System.out.print("失败啦哈哈哈!");
                }
            }
        } catch (Exception e) {

        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int id = myid;

        try {
            String sql3 = "select sc from sc where id = '" + id + "'";
            Statement st2 = DBCon.DBconnec().createStatement();
            ResultSet rs3 = st2.executeQuery(sql3);
            int count3 = 0;
            while (rs3.next()) {
                count3 = rs3.getInt(1);
            }
            if (count3 == 0) {
                JOptionPane.showMessageDialog(this, "课程成绩未更新", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                try {
                    jTextArea1.setText("");
                    Connection sta = DBCon.DBconnec();
                    String s = jTextField11.getText().trim();
                    PreparedStatement ps = sta.prepareStatement("select info.id,info.`name`,course.courseid,course.coursename,course.teacher,course.xz,sc.sc from info,sc,course,susers where info.id =sc.id and sc.courseid=course.courseid and info.id = susers.id and info.id=?");
                    ps.setInt(1, myid);
                    ResultSet rs = ps.executeQuery();
                    while (rs.next()) {
                        int s1 = rs.getInt(1);
                        String s2 = rs.getString(2);
                        String s3 = rs.getString(3);
                        String s4 = rs.getString(4);
                        String s5 = rs.getString(5);
                        String s6 = rs.getString(6);
                        int s7 = rs.getInt(7);
                        jTextArea1.append("学号：" + s1 + " 姓名：" + s2 + "：课程编号：" + s3 + "：课程名称：" + s4 + "：课程教师：" + s5 + "：课程性质：" + s6 + "：成绩：" + s7 + "\r\n");
                    }
                } catch (Exception e) {
                    System.out.print("失败啦哈哈哈!");
                }
            }
        } catch (Exception e) {
            System.out.print("失败啦哈哈哈!");
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField11;
    // End of variables declaration//GEN-END:variables

}
