/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examesystem;

import dbUtil.DbUtil;
import java.awt.HeadlessException;
import java.awt.event.ItemEvent;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel hunt
 */
public class AdministerPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdministerPanel
     */
    public AdministerPanel() {
        initComponents();
        setData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        myInfo = new javax.swing.JPanel();
        genderLable = new javax.swing.JLabel();
        femaleButton = new javax.swing.JRadioButton();
        phoneLable = new javax.swing.JLabel();
        phoneText = new javax.swing.JTextField();
        idLable = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        emailLable1 = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        nameLable = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        maleButton = new javax.swing.JRadioButton();
        editButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();
        passwordLable = new javax.swing.JLabel();
        passwordText = new javax.swing.JPasswordField();
        password2Lable = new javax.swing.JLabel();
        password2Text = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        userQuery = new javax.swing.JTextField();
        userDeleteBtn = new javax.swing.JButton();
        searchUserButton = new javax.swing.JButton();
        userSelect = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        userList = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        scoreSelect = new javax.swing.JComboBox();
        scoreQueryText = new javax.swing.JTextField();
        scoreDeleteBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        scoreList = new javax.swing.JList<>();
        conditionModifierSelect = new javax.swing.JComboBox<>();
        searchGradeButton = new javax.swing.JButton();

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        genderLable.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        genderLable.setText("性别：");

        femaleButton.setText("女");
        femaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleButtonActionPerformed(evt);
            }
        });

        phoneLable.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        phoneLable.setText("电话：");

        idLable.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        idLable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        idLable.setText("学号：");

        emailLable1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        emailLable1.setText("邮箱：");

        nameLable.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        nameLable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameLable.setText("姓名：");

        maleButton.setSelected(true);
        maleButton.setText("男");
        maleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleButtonActionPerformed(evt);
            }
        });

        editButton.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        editButton.setText("修改");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        confirmButton.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        confirmButton.setText("完成");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        passwordLable.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        passwordLable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passwordLable.setText("密码：");

        password2Lable.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        password2Lable.setText("请再输一次：");

        javax.swing.GroupLayout myInfoLayout = new javax.swing.GroupLayout(myInfo);
        myInfo.setLayout(myInfoLayout);
        myInfoLayout.setHorizontalGroup(
            myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myInfoLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(myInfoLayout.createSequentialGroup()
                        .addComponent(editButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirmButton))
                    .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(myInfoLayout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(myInfoLayout.createSequentialGroup()
                                    .addComponent(phoneLable)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(passwordText))
                                .addGroup(myInfoLayout.createSequentialGroup()
                                    .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(genderLable)
                                        .addComponent(nameLable)
                                        .addComponent(emailLable1)
                                        .addComponent(idLable))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(nameText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, myInfoLayout.createSequentialGroup()
                                            .addComponent(maleButton)
                                            .addGap(18, 18, 18)
                                            .addComponent(femaleButton))
                                        .addComponent(idText, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(emailText)))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myInfoLayout.createSequentialGroup()
                            .addComponent(passwordLable, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(phoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(myInfoLayout.createSequentialGroup()
                        .addComponent(password2Lable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(password2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        myInfoLayout.setVerticalGroup(
            myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myInfoLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLable)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(genderLable)
                    .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(maleButton)
                        .addComponent(femaleButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLable1)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLable))
                .addGap(18, 18, 18)
                .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLable))
                .addGap(16, 16, 16)
                .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password2Lable))
                .addGap(33, 33, 33)
                .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton)
                    .addComponent(editButton))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("我的信息", myInfo);

        userQuery.setText("请输入搜索条件");

        userDeleteBtn.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        userDeleteBtn.setText("删除");
        userDeleteBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        userDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userDeleteBtnActionPerformed(evt);
            }
        });

        searchUserButton.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        searchUserButton.setText("搜索");
        searchUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchUserButtonActionPerformed(evt);
            }
        });

        userSelect.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        userSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "请选择", "id", "name", "sex", "idcard", "phone", "email" }));
        userSelect.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                userSelectItemStateChanged(evt);
            }
        });

        userList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        userList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(userList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(userSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(userQuery)
                        .addGap(18, 18, 18)
                        .addComponent(searchUserButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(78, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userDeleteBtn)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(48, 48, 48))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userQuery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchUserButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(userDeleteBtn)
                .addGap(29, 29, 29))
        );

        jTabbedPane1.addTab("管理用户", jPanel2);

        scoreSelect.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        scoreSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "请选择", "id", "name", "sex", "grade", "phone", "email" }));
        scoreSelect.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                scoreSelectItemStateChanged(evt);
            }
        });

        scoreQueryText.setText("请输入搜索条件");

        scoreDeleteBtn.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        scoreDeleteBtn.setText("删除");
        scoreDeleteBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        scoreDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreDeleteBtnActionPerformed(evt);
            }
        });

        scoreList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(scoreList);

        conditionModifierSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "请选择", "大于", "小于", "等于" }));
        conditionModifierSelect.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                conditionModifierSelectItemStateChanged(evt);
            }
        });

        searchGradeButton.setText("搜索");
        searchGradeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchGradeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scoreDeleteBtn)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(scoreSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(conditionModifierSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(scoreQueryText)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(searchGradeButton))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreQueryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scoreSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conditionModifierSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchGradeButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(scoreDeleteBtn)
                .addContainerGap())
        );

        jTabbedPane1.addTab("管理成绩", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void femaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleButtonActionPerformed
        // TODO add your handling code here:
        gender = 0;
    }//GEN-LAST:event_femaleButtonActionPerformed

    private void maleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleButtonActionPerformed
        // TODO add your handling code here:
        gender = 1;
    }//GEN-LAST:event_maleButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        passwordText.setEditable(true);
        password2Text.setEditable(true);
        emailText.setEditable(true);
        phoneText.setEditable(true);
        maleButton.setEnabled(true);
        femaleButton.setEnabled(true);
    }//GEN-LAST:event_editButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        String p1 = passwordText.getText().trim();
        String p2 = password2Text.getText().trim();
        String email = emailText.getText().trim();
        String phone = phoneText.getText().trim();
        Pattern p = Pattern.compile("^1[34578]\\d{9}$");    // 正则表达式// 正则表达式验证手机号
        Matcher m = p.matcher(phone);
        Pattern pattern = Pattern.compile("^([a-zA-Z0-9_\\-\\.]+)@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\\]?)$");
        Matcher emm = pattern.matcher(email);
        if (email.isEmpty() || phone.isEmpty() || p1.isEmpty() || p2.isEmpty()) {
            JOptionPane.showMessageDialog(this, "注册信息不能为空", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!p1.equals(p2)) {
            JOptionPane.showMessageDialog(this, "密码不一致", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (m.matches() != true) {
            JOptionPane.showMessageDialog(this, "手机号输入错误", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (emm.matches() != true) {
            JOptionPane.showMessageDialog(this, "邮箱输入错误", "Error", JOptionPane.ERROR_MESSAGE);
        }else if (p1.length() < 6) {
            JOptionPane.showMessageDialog(this, "密码不得少于6位", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                PreparedStatement ps = DbUtil.getStatement("update user set sex=?,email=?,phone=?,password=? where id = ?");
                ps.setInt(1, gender);
                ps.setString(2, email);
                ps.setString(3, phone);
                ps.setString(4, p1);
                ps.setString(5, id);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "修改成功！", "Succesed", JOptionPane.INFORMATION_MESSAGE);
            } catch (HeadlessException | SQLException e) {
                System.out.print("eeeee!");
            }
        }
        passwordText.setEditable(false);
        password2Text.setEditable(false);
        emailText.setEditable(false);
        phoneText.setEditable(false);
        maleButton.setEnabled(false);
        femaleButton.setEnabled(false);
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void userDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userDeleteBtnActionPerformed
        // TODO add your handling code here:
        String userDel = userList.getSelectedValue();
        if(userDel == null){
            return;
        }
        int endIndex = userDel.indexOf(" name:");
        String userDelId = userDel.substring(3, --endIndex);
        try {
            PreparedStatement ps = DbUtil.getStatement("delete from user where id = ?");
            ps.setString(1, userDelId);
            ps.execute();
        } catch (SQLException ex) {
            Logger.getLogger(AdministerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_userDeleteBtnActionPerformed

    private void searchUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchUserButtonActionPerformed
        // TODO add your handling code here:
        users.clear();
        String[] empty = {" "};
        userList.setListData(empty);
        String searchKey = userQuery.getText();
        try {
            PreparedStatement ps = DbUtil.getStatement("select * from user where "+searchCondition+"=?");
            ps.setString(1, searchKey);
            ResultSet result = ps.executeQuery();
            while(result.next()){
                StringBuilder userStr = new StringBuilder();
                long id = result.getLong("id");
                String name = result.getString("name");
                String sex = result.getString("sex").equals("0")?"男":"女";
                String idCard = result.getString("idcard");
                String phone = result.getString("phone");
                String email = result.getString("email");
                String user = userStr.append("id:").append(id)
                        .append(" name:").append(name)
                        .append(" idCard:").append(idCard)
                        .append(" phone:").append(phone)
                        .append(" email:").append(email).toString();
                users.add(user);
            }
            userList.setListData((String[])users.toArray());
        } catch (SQLException ex) {
            Logger.getLogger(AdministerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchUserButtonActionPerformed

    private void userSelectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_userSelectItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            searchCondition = userSelect.getSelectedItem().toString();
        }
    }//GEN-LAST:event_userSelectItemStateChanged

    private void scoreSelectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_scoreSelectItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            searchCondition = scoreSelect.getSelectedItem().toString();
        }
    }//GEN-LAST:event_scoreSelectItemStateChanged

    private void scoreDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreDeleteBtnActionPerformed
        // TODO add your handling code here:
        String scoreDel = scoreList.getSelectedValue();
        if(scoreDel == null){
            return;
        }
        int endIndex = scoreDel.indexOf(" name:");
        String scoreDelId = scoreDel.substring(3, --endIndex);
        try {
            PreparedStatement ps = DbUtil.getStatement("delete from score where id = ?");
            ps.setString(1, scoreDelId);
            ps.execute();
        } catch (SQLException ex) {
            Logger.getLogger(AdministerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_scoreDeleteBtnActionPerformed

    private void conditionModifierSelectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_conditionModifierSelectItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            conditionModifier = conditionModifierSelect.getSelectedItem().toString();
        }
    }//GEN-LAST:event_conditionModifierSelectItemStateChanged

    private void searchGradeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchGradeButtonActionPerformed
        // TODO add your handling code here:
        String[] empty = {" "};
        scoreList.setListData(empty);
        scores.clear();
        String scoreSearch = "select score.*, users.name from score inner join users on score.id =  where"
                + scoreSelect + conditionModifier + scoreQueryText.getText();
        
        try {
            Statement statement = DbUtil.getSqlStatement();
            ResultSet result = statement.executeQuery(scoreSearch);
            while(result.next()){
                StringBuilder scoreBuilder = new StringBuilder();
                String id = result.getString("id");
                String score = result.getString("score");
                String time = result.getString("time");
                String name = result.getString("name");
                String scoreStr = scoreBuilder.append("id:").append(id)
                        .append("name:").append(name)
                        .append("score:").append(score)
                        .append("time:").append(time).toString();
                scores.add(score);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdministerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        scoreList.setListData((String[])scores.toArray());
    }//GEN-LAST:event_searchGradeButtonActionPerformed

    private void setData() {
        id = MainFrame.datas.get("id");
        try {
            PreparedStatement ps = DbUtil.getStatement("select * from user where id = ?");
            PreparedStatement scorePs = DbUtil.getStatement("select * from users");
            scorePs.setString(1, id);
            ps.setString(1, id);
            //填充用户信息
            ResultSet result = ps.executeQuery();
            if(result.next()){
               String name = result.getString("name");
               String sex = result.getString("sex");
               String phone = result.getString("phone");
               String email = result.getString("email");
               String password = result.getString("password");
               idText.setText(id);
               nameText.setText(name);
               emailText.setText(email);
               phoneText.setText(phone);
               passwordText.setText("password");
               password2Text.setText("password");
               if("0".equals(sex)){
                   maleButton.setSelected(true);
                   femaleButton.setSelected(false);
               }else{
                   maleButton.setSelected(false);
                   femaleButton.setSelected(true);
               }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(StudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private String searchCondition;
    private int gender;
    private String id;
    private ArrayList<String> users;
    private ArrayList<String> scores;
    private String conditionModifier;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> conditionModifierSelect;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel emailLable1;
    private javax.swing.JTextField emailText;
    private javax.swing.JRadioButton femaleButton;
    private javax.swing.JLabel genderLable;
    private javax.swing.JLabel idLable;
    private javax.swing.JTextField idText;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton maleButton;
    private javax.swing.JPanel myInfo;
    private javax.swing.JLabel nameLable;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel password2Lable;
    private javax.swing.JPasswordField password2Text;
    private javax.swing.JLabel passwordLable;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JLabel phoneLable;
    private javax.swing.JTextField phoneText;
    private javax.swing.JButton scoreDeleteBtn;
    private javax.swing.JList<String> scoreList;
    private javax.swing.JTextField scoreQueryText;
    private javax.swing.JComboBox scoreSelect;
    private javax.swing.JButton searchGradeButton;
    private javax.swing.JButton searchUserButton;
    private javax.swing.JButton userDeleteBtn;
    private javax.swing.JList<String> userList;
    private javax.swing.JTextField userQuery;
    private javax.swing.JComboBox userSelect;
    // End of variables declaration//GEN-END:variables
}
