/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examesystem;

import dbUtil.DbUtil;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class RegisterPanel extends javax.swing.JPanel {


    /**
     * Creates new form FristJPanel
     */
    public RegisterPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        titileLabel = new javax.swing.JLabel();
        nameLable = new javax.swing.JLabel();
        passwordLable = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        passwordText = new javax.swing.JPasswordField();
        confirmButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        password2Lable = new javax.swing.JLabel();
        password2Text = new javax.swing.JPasswordField();
        genderLable = new javax.swing.JLabel();
        phoneLable = new javax.swing.JLabel();
        phoneText = new javax.swing.JTextField();
        idLable = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        emailLable1 = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        genderRadioBtn1 = new javax.swing.JRadioButton();
        genderRadioBtn2 = new javax.swing.JRadioButton();
        idcardLable = new javax.swing.JLabel();
        idcardText = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(800, 500));

        titileLabel.setFont(new java.awt.Font("华文行楷", 1, 36)); // NOI18N
        titileLabel.setForeground(new java.awt.Color(0, 153, 153));
        titileLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titileLabel.setText("欢迎注册考试管理系统");

        nameLable.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        nameLable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameLable.setText("姓名：");

        passwordLable.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        passwordLable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passwordLable.setText("密码：");

        confirmButton.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        confirmButton.setText("确定");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        resetButton.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        resetButton.setText("重置");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        password2Lable.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        password2Lable.setText("请再输一次：");

        genderLable.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        genderLable.setText("性别：");

        phoneLable.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        phoneLable.setText("电话：");

        idLable.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        idLable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        idLable.setText("学号：");

        emailLable1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        emailLable1.setText("邮箱：");

        buttonGroup1.add(genderRadioBtn1);
        genderRadioBtn1.setSelected(true);
        genderRadioBtn1.setText("男");
        genderRadioBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderRadioBtn1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(genderRadioBtn2);
        genderRadioBtn2.setText("女");
        genderRadioBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderRadioBtn2ActionPerformed(evt);
            }
        });

        idcardLable.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        idcardLable.setText("身份证号：");

        idcardText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idcardTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(confirmButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resetButton)
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(genderLable)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nameLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(idLable))
                            .addComponent(emailLable1)
                            .addComponent(idcardLable)
                            .addComponent(phoneLable)
                            .addComponent(password2Lable)
                            .addComponent(passwordLable, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(phoneText)
                            .addComponent(password2Text, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idcardText)
                            .addComponent(nameText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idText)
                            .addComponent(emailText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(genderRadioBtn1)
                                .addGap(18, 18, 18)
                                .addComponent(genderRadioBtn2)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(137, 137, 137))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(titileLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLable1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idcardText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idcardLable)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idLable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameLable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(genderLable)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(genderRadioBtn1)
                                .addComponent(genderRadioBtn2)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneLable))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password2Lable)
                    .addComponent(password2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetButton)
                    .addComponent(confirmButton))
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        String p1 = passwordText.getText().trim();
        String p2 = password2Text.getText().trim();
        String name = nameText.getText().trim();
        String email = emailText.getText().trim();
        String phone = phoneText.getText().trim();
        String id = idText.getText().trim();
        String idcard = idcardText.getText().trim();
        Pattern p = Pattern.compile("^1[34578]\\d{9}$");    // 正则表达式// 正则表达式验证手机号
        Matcher m = p.matcher(phone);
        Pattern pattern = Pattern.compile("^([a-zA-Z0-9_\\-\\.]+)@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\\]?)$");
        Matcher emm = pattern.matcher(email);
        if (name.isEmpty() || email.isEmpty() || phone.isEmpty() || p1.isEmpty() || p2.isEmpty()) {
            JOptionPane.showMessageDialog(this, "注册信息不能为空", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!p1.equals(p2)) {
            JOptionPane.showMessageDialog(this, "密码不一致", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (m.matches() != true) {
            JOptionPane.showMessageDialog(this, "手机号输入错误", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (emm.matches() != true) {
            JOptionPane.showMessageDialog(this, "邮箱输入错误", "Error", JOptionPane.ERROR_MESSAGE);
        }else if (p1.length() < 6) {
            JOptionPane.showMessageDialog(this, "密码不得少于6位", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                PreparedStatement ps = DbUtil.getStatement("insert into users(id,name,sex,email,phone,password,root,idcard) values(?,?,?,?,?,?,0,?)");
                ps.setString(1, id);//去替代上面的几个问号
                ps.setString(2, name);
                ps.setInt(3, gender);
                ps.setString(4, email);
                ps.setString(5, phone);
                ps.setString(6, p1);
                ps.setString(7,idcard);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "注册成功！请点击【确定】返回登录界面登录", "Succesed", JOptionPane.INFORMATION_MESSAGE);
                Login lg = new Login();
                MainFrame.mainFrame.remove( MainFrame.mainFrame.getContentPane());
                MainFrame.mainFrame.setContentPane(lg);
                MainFrame.mainFrame.validate();
            } catch (Exception e) {
                e.printStackTrace();
                System.out.print("eeeee!");
            }
        }

    }//GEN-LAST:event_confirmButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        idText.setText("");
        nameText.setText("");
        emailText.setText("");
        phoneText.setText("");
        passwordText.setText("");
        password2Text.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void genderRadioBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderRadioBtn2ActionPerformed
        // TODO add your handling code here:
        gender = 0;   
    }//GEN-LAST:event_genderRadioBtn2ActionPerformed

    private void genderRadioBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderRadioBtn1ActionPerformed
        // TODO add your handling code here:
        gender = 1;
    }//GEN-LAST:event_genderRadioBtn1ActionPerformed

    private void idcardTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idcardTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idcardTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel emailLable1;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel genderLable;
    private javax.swing.JRadioButton genderRadioBtn1;
    private javax.swing.JRadioButton genderRadioBtn2;
    private javax.swing.JLabel idLable;
    private javax.swing.JTextField idText;
    private javax.swing.JLabel idcardLable;
    private javax.swing.JTextField idcardText;
    private javax.swing.JLabel nameLable;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel password2Lable;
    private javax.swing.JPasswordField password2Text;
    private javax.swing.JLabel passwordLable;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JLabel phoneLable;
    private javax.swing.JTextField phoneText;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel titileLabel;
    // End of variables declaration//GEN-END:variables
    int flag = 2;
    private int gender = 0;
}
