/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examesystem;

import dbUtil.DbUtil;
import java.awt.HeadlessException;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel hunt
 */
public class StudentPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentPanel
     */
    public StudentPanel() {
        initComponents();
        setData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        studentPanel = new javax.swing.JTabbedPane();
        myInfo = new javax.swing.JPanel();
        genderLable = new javax.swing.JLabel();
        femaleButton = new javax.swing.JRadioButton();
        phoneLable = new javax.swing.JLabel();
        idLable = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        emailLable1 = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        nameLable = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        maleButton = new javax.swing.JRadioButton();
        editButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();
        passwordLable = new javax.swing.JLabel();
        password2Lable = new javax.swing.JLabel();
        password2Text = new javax.swing.JPasswordField();
        changeUserBtn = new javax.swing.JButton();
        idCardLable = new javax.swing.JLabel();
        idCardText = new javax.swing.JTextField();
        passwordText = new javax.swing.JPasswordField();
        phoneText = new javax.swing.JTextField();
        myTest = new javax.swing.JPanel();
        startExamButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        myScore = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        scoreList = new javax.swing.JList<>();

        studentPanel.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        genderLable.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        genderLable.setText("性别：");

        buttonGroup1.add(femaleButton);
        femaleButton.setText("女");
        femaleButton.setEnabled(false);
        femaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleButtonActionPerformed(evt);
            }
        });

        phoneLable.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        phoneLable.setText("电话：");

        idLable.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        idLable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        idLable.setText("学号：");

        idText.setEditable(false);

        emailLable1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        emailLable1.setText("邮箱：");

        emailText.setEditable(false);

        nameLable.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        nameLable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameLable.setText("姓名：");

        nameText.setEditable(false);

        buttonGroup1.add(maleButton);
        maleButton.setSelected(true);
        maleButton.setText("男");
        maleButton.setEnabled(false);
        maleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleButtonActionPerformed(evt);
            }
        });

        editButton.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        editButton.setText("修改");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        confirmButton.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        confirmButton.setText("完成");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        passwordLable.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        passwordLable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passwordLable.setText("密码：");

        password2Lable.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        password2Lable.setText("请再输一次：");

        password2Text.setEditable(false);

        changeUserBtn.setText("注销");
        changeUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeUserBtnActionPerformed(evt);
            }
        });

        idCardLable.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        idCardLable.setText("身份证号：");

        idCardText.setEditable(false);
        idCardText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCardTextActionPerformed(evt);
            }
        });

        passwordText.setEditable(false);
        passwordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextActionPerformed(evt);
            }
        });

        phoneText.setEditable(false);

        javax.swing.GroupLayout myInfoLayout = new javax.swing.GroupLayout(myInfo);
        myInfo.setLayout(myInfoLayout);
        myInfoLayout.setHorizontalGroup(
            myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myInfoLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(genderLable)
                    .addComponent(nameLable)
                    .addComponent(emailLable1)
                    .addComponent(idLable)
                    .addComponent(idCardLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myInfoLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(editButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confirmButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(myInfoLayout.createSequentialGroup()
                        .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nameText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, myInfoLayout.createSequentialGroup()
                                .addComponent(maleButton)
                                .addGap(18, 18, 18)
                                .addComponent(femaleButton))
                            .addComponent(idText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailText)
                            .addComponent(idCardText))
                        .addContainerGap(161, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myInfoLayout.createSequentialGroup()
                        .addComponent(changeUserBtn)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myInfoLayout.createSequentialGroup()
                        .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordLable, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneLable)
                            .addComponent(password2Lable))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(password2Text, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                            .addComponent(phoneText)
                            .addComponent(passwordText))
                        .addGap(161, 161, 161))))
        );
        myInfoLayout.setVerticalGroup(
            myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myInfoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(changeUserBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLable)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(genderLable)
                    .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(maleButton)
                        .addComponent(femaleButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLable1)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idCardLable)
                    .addComponent(idCardText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLable)
                    .addComponent(phoneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLable)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password2Lable)
                    .addComponent(password2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(myInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton)
                    .addComponent(editButton))
                .addGap(61, 61, 61))
        );

        studentPanel.addTab("我的信息", myInfo);

        myTest.setToolTipText("");

        startExamButton.setText("开始考试");
        startExamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startExamButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel1.setText("欢迎参加本次考试，点击下方开始按钮开始考试");

        javax.swing.GroupLayout myTestLayout = new javax.swing.GroupLayout(myTest);
        myTest.setLayout(myTestLayout);
        myTestLayout.setHorizontalGroup(
            myTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myTestLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(myTestLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(startExamButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        myTestLayout.setVerticalGroup(
            myTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myTestLayout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(startExamButton)
                .addGap(119, 119, 119))
        );

        studentPanel.addTab("我的考试", myTest);

        scoreList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scoreList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(scoreList);

        jScrollPane1.setViewportView(jScrollPane2);

        javax.swing.GroupLayout myScoreLayout = new javax.swing.GroupLayout(myScore);
        myScore.setLayout(myScoreLayout);
        myScoreLayout.setHorizontalGroup(
            myScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myScoreLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                .addContainerGap())
        );
        myScoreLayout.setVerticalGroup(
            myScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myScoreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                .addContainerGap())
        );

        studentPanel.addTab("我的成绩", myScore);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startExamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startExamButtonActionPerformed
        // TODO add your handling code here:
        ExamPanel examPanel = new ExamPanel();
        MainFrame.mainFrame.remove(MainFrame.mainFrame.getContentPane());
        MainFrame.mainFrame.setContentPane(examPanel);
        MainFrame.mainFrame.validate();
    }//GEN-LAST:event_startExamButtonActionPerformed

    private void passwordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextActionPerformed

    private void idCardTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCardTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idCardTextActionPerformed

    private void changeUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeUserBtnActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        MainFrame.mainFrame.remove(MainFrame.mainFrame.getContentPane());
        MainFrame.mainFrame.setContentPane(login);
        MainFrame.mainFrame.validate();
    }//GEN-LAST:event_changeUserBtnActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        String p1 = passwordText.getText().trim();
        String p2 = password2Text.getText().trim();
        String email = emailText.getText().trim();
        String phone = phoneText.getText().trim();
        Pattern p = Pattern.compile("^1[34578]\\d{9}$");    // 正则表达式// 正则表达式验证手机号
        Matcher m = p.matcher(phone);
        Pattern pattern = Pattern.compile("^([a-zA-Z0-9_\\-\\.]+)@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\\]?)$");
        Matcher emm = pattern.matcher(email);
        if (email.isEmpty() || phone.isEmpty() || p1.isEmpty() || p2.isEmpty()) {
            JOptionPane.showMessageDialog(this, "注册信息不能为空", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!p1.equals(p2)) {
            JOptionPane.showMessageDialog(this, "密码不一致", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (m.matches() != true) {
            JOptionPane.showMessageDialog(this, "手机号输入错误", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (emm.matches() != true) {
            JOptionPane.showMessageDialog(this, "邮箱输入错误", "Error", JOptionPane.ERROR_MESSAGE);
        }else if (p1.length() < 6) {
            JOptionPane.showMessageDialog(this, "密码不得少于6位", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                PreparedStatement ps = DbUtil.getStatement("update users set sex=?,email=?,phone=?,password=? where id = ?");
                ps.setInt(1, gender);
                ps.setString(2, email);
                ps.setString(3, phone);
                ps.setString(4, p1);
                ps.setString(5, id);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "修改成功！", "Succesed", JOptionPane.INFORMATION_MESSAGE);
            } catch (HeadlessException | SQLException e) {
                e.printStackTrace();
                System.out.print("eeeee!");
            }
        }
        changeEditable(false);
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        changeEditable(true);
    }//GEN-LAST:event_editButtonActionPerformed

    private void maleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleButtonActionPerformed
        // TODO add your handling code here:
        gender = 1;
    }//GEN-LAST:event_maleButtonActionPerformed

    private void femaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleButtonActionPerformed
        // TODO add your handling code here:
        gender = 0;
    }//GEN-LAST:event_femaleButtonActionPerformed

private int gender = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton changeUserBtn;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel emailLable1;
    private javax.swing.JTextField emailText;
    private javax.swing.JRadioButton femaleButton;
    private javax.swing.JLabel genderLable;
    private javax.swing.JLabel idCardLable;
    private javax.swing.JTextField idCardText;
    private javax.swing.JLabel idLable;
    private javax.swing.JTextField idText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton maleButton;
    private javax.swing.JPanel myInfo;
    private javax.swing.JPanel myScore;
    private javax.swing.JPanel myTest;
    private javax.swing.JLabel nameLable;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel password2Lable;
    private javax.swing.JPasswordField password2Text;
    private javax.swing.JLabel passwordLable;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JLabel phoneLable;
    private javax.swing.JTextField phoneText;
    private javax.swing.JList<String> scoreList;
    private javax.swing.JButton startExamButton;
    private javax.swing.JTabbedPane studentPanel;
    // End of variables declaration//GEN-END:variables

    private String id;
    
    private void setData() {
        idText.setEditable(true);
        nameText.setEditable(true);
        changeEditable(true);
        id = MainFrame.datas.get("id");
        try {
            PreparedStatement ps = DbUtil.getStatement("select * from users where id = ?");
            PreparedStatement scorePs = DbUtil.getStatement("select * from score where id = ?");
            scorePs.setString(1, id);
            ps.setString(1, id);
            //填充用户信息
            ResultSet result = ps.executeQuery();
            if(result.next()){
               String name = result.getString("name");
               String sex = result.getString("sex");
               String phone = result.getString("phone");
               String email = result.getString("email");
               String idCard = result.getString("idcard");
               String password = result.getString("password");
               idText.setText(id);
               nameText.setText(name);
               emailText.setText(email);
               passwordText.setText(password);
               phoneText.setText(phone);
               password2Text.setText(password);
               idCardText.setText(idCard);
               if("0".equals(sex)){
                   maleButton.setSelected(true);
                   femaleButton.setSelected(false);
               }else{
                   maleButton.setSelected(false);
                   femaleButton.setSelected(true);
               }
            }
            //填充用户分数
            ResultSet scoreResult = scorePs.executeQuery();
            ArrayList<String> scores = new ArrayList<>();
            while(result.next()){
                String score = scoreResult.getString("score");
                Date time = scoreResult.getDate("time");
                String exameResult = score + ":" + time.toString();
                scores.add(exameResult);
            }
            String[] empty = {" "};
            String[] scoresArray = scores.isEmpty() ? empty:(String[])scores.toArray();
            scoreList.setListData(scoresArray);
        } catch (SQLException ex) {
            Logger.getLogger(StudentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        changeEditable(false);
        idText.setEditable(false);
        nameText.setEditable(false);
    }
    
    private void changeEditable(boolean isEditable){
        phoneText.setEditable(isEditable);
        password2Text.setEditable(isEditable);
        emailText.setEditable(isEditable);
        passwordText.setEditable(isEditable);
        maleButton.setEnabled(isEditable);
        femaleButton.setEnabled(isEditable);
        idCardText.setEditable(isEditable);
    }
}
